const carKids: string = '/../assets/img/icons/car-kid.png';
const carAdult: string = '/../assets/img/icons/car-adult.png';
export const PRICES: { hidden: boolean, car: string, name: string, kind: string, audience: string, price: string, description: string }[] = [
	{ hidden: false, car: carKids, name: 'Terapia indywidualna', kind: '60 minut', audience: 'DLA DZIECKA', price: '100zł', description: '1h spotkania dziecka z terapeutą, podczas którego realizowany jest indywidualny program edukacyjno-terapeutyczny, poprzedzony diagnozą funkcjonalną.' },
	{ hidden: true, car: carKids, name: 'Terapia indywidualna', kind: 'Pakiet 10h', audience: 'DLA DZIECKA', price: '900zł', description: 'W skład pakietu wchodzi 10 spotkań po 60 minut. Termin realizacji to 5 tygodni. Decydując się na ten wariant oszczędzasz wartość pojedynczej sesji indywidualnej.' },
	{ hidden: true, car: carKids, name: 'Terapia indywidualna', kind: '10 wizyt po 2h', audience: 'DLA DZIECKA', price: '1600zł', description: 'W skład pakietu wchodzi 10 spotkań trwających przez 2 godziny. Termin realizacji pakietu to 5 tygodni.' },
	{ hidden: true, car: carKids, name: 'Konsultacja domowa', kind: '60 minut', audience: 'DLA DZIECKA', price: '180zł', description: '1h spotkania dziecka z terapeutą w domu podopiecznego. Cel wizyty jest uzależniony od aktualnych potrzeb rodziców.' },
	{ hidden: true, car: carKids, name: 'Diagnoza<br>VB-MAPP', kind: 'Test VB-MAPP', audience: 'DLA DZIECKA', price: '900zł', description: 'Ocena poziomu funkcjonowania dziecka za pomocą testu "VB-MAPP - Ocena osiągania kamieni milowych rozwoju i planowanie terapii" + raport.' },
	{ hidden: true, car: carKids, name: 'Diagnoza<br>„PEP-R”', kind: 'Test PEP-R', audience: 'DLA DZIECKA', price: '500zł', description: 'Test jest przeznaczony dla dzieci w wieku od 6 miesięcy do 7 lat. Ocena poziomu funkcjonowania dziecka za pomocą testu „PEP-R” + raport.' },
	{ hidden: true, car: carKids, name: 'Umiejętności społeczne', kind: '60 minut', audience: 'DLA DZIECKA', price: '80zł', description: '1h spotkania dwójki dzieci z terapeutą w celu ćwiczenia umiejętności społecznych dopasowanych do poziomu dziecka. 80 zł to cena za jedno dziecko.' },
	{ hidden: false, car: carAdult, name: 'Indywidualne warsztaty', kind: '60 minut', audience: 'DLA RODZICA', price: '60zł', description: '1h spotkania z terapeutą w celu przećwiczenia technik pracy z dzieckiem, do zastosowania we własnym zakresie. Warsztat dotyczy aktualnie rozwijanych umiejętności u dziecka w trakcie terapii.' },
	{ hidden: true, car: carAdult, name: 'Warsztaty<br>/szkolenia', kind: 'Grupowe', audience: 'DLA RODZICA', price: 'Cena zależna <br>od tematyki szkolenia', description: 'Cyklicznie organizowane szkolenia /warsztaty grupowe dla rodziców. Informację na temat aktualnie realizowanych spotkań znajdziecie Państwo na naszej stronie fb.' }
];