export const TEAM: { image: string, position: string, name: string, description: string }[] = [
	{ image: '/../assets/img/joanna-smieja.png', position: 'Terapeuta, kierownik merytoryczny', name: 'Joanna Śmieja', description: `Terapeuta, certyfikowany analityk zachowania, magister prawa. Jej pasja to praca z ludźmi, a zwłaszcza z dziećmi. Uwielbia się rozwijać i zdobywać nowe doświadczenia. Prywatnie spełnia się jako fotograf i amator muzyki każdego gatunku.<br>
	Ukończyła California State University Stanislaus (Turlock, USA) jako magister psychologii, z naciskiem na Stosowaną Analizę Zachowania (ABA), Bangor University (Bangor, Walia) jako magister Stosowanej Analizy Zachowania (ABA), Uniwersytet SWPS, Wydział Zamiejscowy we Wrocławiu jako magister psychologii, podyplomową Akademię Mediatora jak również Uniwersytet Wrocławski, Wydział Prawa, Administracji i Ekonomii jako magister prawa.<br>
	Odbyła szkolenia z zakresu oceny umiejętności i planowania terapii VB-MAPP, konstruowania planów terapeutycznych w ramach profilu psychoedukacyjnego PEP-R oraz PECS (poziom 1). Zdobyła Certyfikat BCBA oraz polską licencję terapeuty behawioralnego. <br>
	Przez lata zdobywała doświadczenie w zakresie prowadzenia terapii dziecięcej w nurcie analizy zachowania m.in. w The Kendall Center (Modesto, USA), Niepublicznym Przedszkolu Integracyjnym „Iskierka” (Warszawa) oraz  w Fundacji „Krok po Kroku“ (Fundacja na rzecz dzieci z zaburzeniami rozwoju i ich rodzin w Warszawie prowadząca szkołę, przedszkole i gabinet terapeutyczny). Pracowała jako terapeuta, szkoleniowiec, nauczyciel wspomagający i konsultant. Umiejętności szkoleniowe zdobyła również prowadząc fakultet na Uniwersytecie SWPS Wydział Zamiejscowy w Katowicach w ramach zajęć z Podstawy Stosowanej Analizy Zachowania.<br>
	Wielokrotnie uczestniczyła w akcjach wolontaryjnych m.in. w Fundacji Synapsis oraz Fundacji Krok po Kroku poszerzając swoje umiejętności i zdobywając doświadczenie.` },
	{ image: '/../assets/img/agnieszka-kobel.png', position: 'Manager', name: 'Agnieszka Kobel', description: `Analityk danych, specjalista od marketingu, mama. Absolwentka Politechniki Wrocławskiej na kierunku Zarządzanie. Swoje doświadczenie zdobyła jako pracownik korporacji w zakresie badań zadowolenia pracowników (Bank BZ WBK we Wrocławiu), reklamy oraz SEO i SEM (Lemon Sky we Wrocławiu), analityk danych marketingowych oraz team leader zespołu raportowego (Credit Suisse we Wrocławiu). <br>
	Prywatnie entuzjastka fotografii i dobrej muzyki, jak również domorosła krawcowa. 
	Dzięki wychowaniu 2 dzieci dopracowała do perfekcji wielozadaniowość i zdolności organizacyjnie.` },
	{ image: '/../assets/img/monika-pelszyk.png', position: 'Superwizor', name: 'Monika Pełszyk', description: `Psycholog ze specjalizacją społeczna psychologia kliniczna. Absolwentka studiów podyplomowych ze Stosowanej Analizy Zachowania. Licencjonowany terapeuta behawioralny, superwizor i szkoleniowiec PLTB. Współpracuje z Fundacją Krok po Kroku – Fundacją na Recz Dzieci z Zaburzeniami Rozwoju i ich Rodzin od 2011 roku. Prowadzi szkolenia dla rodziców i profesjonalistów z zakresu Stosowanej Analizy Zachowania w ramach Polskiej Licencji Terapeuty Behawioralnego. Pracuje jako wykładowca na Uniwersytecie SWPS w Warszawie, prowadząc zajęcia w ramach studiów podyplomowych „Stosowana Analiza Zachowania: przygotowanie do pracy z osobami z zaburzeniami rozwoju i zachowania”. Specjalizuje się w pracy nad zachowaniami trudnymi i uczeniu umiejętności społecznych. W życiu prywatnym z pasją oddaje się urządzaniu mieszkań.` }
];