export const TEAM: { image: string, position: string, name: string, description: string }[] = [
	{ image: '/../assets/img/joanna-smieja.png', position: 'Terapeuta, kierownik merytoryczny', name: 'Joanna Śmieja', description: `Psycholog, terapeuta, certyfikowany analityk zachowania. Jej pasja to praca z ludźmi, a zwłaszcza z dziećmi.<br>
	Absolwentka psychologii na California State University Stanislaus (Turlock, USA) oraz na Uniwersytecie SWPS we Wrocławiu. Ukończyła studia magisterskie z zakresu Stosowanej Analizy Zachowania na Bangor University (Bangor, Walia) oraz studia podyplomowe Akademia Mediatora na Uniwersytecie SWPS we Wrocławiu.<br>
	Przez lata zdobywała doświadczenie w zakresie prowadzenia terapii dziecięcej w nurcie analizy zachowania m.in. w The Kendall Center (Modesto, USA), Niepublicznym Przedszkolu Integracyjnym „Iskierka” (Warszawa) oraz w Fundacji „Krok po Kroku“ (Fundacja na rzecz dzieci z zaburzeniami rozwoju i ich rodzin w Warszawie prowadząca szkołę, przedszkole i gabinet terapeutyczny). Pracowała jako terapeuta, szkoleniowiec, nauczyciel wspomagający i konsultant. Umiejętności szkoleniowe zdobyła również prowadząc fakultet na Uniwersytecie SWPS Wydział Zamiejscowy w Katowicach w ramach zajęć z Podstaw Stosowanej Analizy Zachowania.<br>
	Wielokrotnie uczestniczyła w akcjach wolontaryjnych m.in. w Fundacji Synapsis oraz Fundacji Krok po Kroku poszerzając swoje umiejętności i zdobywając doświadczenie.<br>
	Odbyła szkolenia z zakresu oceny umiejętności i planowania terapii VB-MAPP, konstruowania planów terapeutycznych w ramach Profilu Psychoedukacyjnego PEP-R oraz komunikacji alternatywnej PECS (poziom 1). Zdobyła Certyfikat BCBA oraz polską licencję terapeuty behawioralnego.<br>
	Prywatnie spełnia się jako fotograf oraz amator muzyki każdego gatunku.` },
	{ image: '/../assets/img/agnieszka-kobel.png', position: 'Manager', name: 'Agnieszka Kobel', description: `Analityk danych, specjalista od marketingu, mama. Absolwentka Politechniki Wrocławskiej na kierunku Zarządzanie. Swoje doświadczenie zdobyła jako pracownik korporacji w zakresie badań zadowolenia pracowników (Bank BZ WBK we Wrocławiu), reklamy oraz SEO i SEM (Lemon Sky we Wrocławiu), analityk danych marketingowych oraz team leader zespołu raportowego (Credit Suisse we Wrocławiu). <br>
	Prywatnie entuzjastka fotografii i dobrej muzyki, jak również domorosła krawcowa. 
	Dzięki wychowaniu 2 dzieci dopracowała do perfekcji wielozadaniowość i zdolności organizacyjnie.` },
	{ image: '/../assets/img/monika-pelszyk.png', position: 'Superwizor', name: 'Monika Pełszyk', description: `Psycholog ze specjalizacją społeczna psychologia kliniczna. Absolwentka studiów podyplomowych ze Stosowanej Analizy Zachowania. Licencjonowany terapeuta behawioralny, superwizor i szkoleniowiec PLTB. Współpracuje z Fundacją Krok po Kroku – Fundacją na Recz Dzieci z Zaburzeniami Rozwoju i ich Rodzin od 2011 roku. Prowadzi szkolenia dla rodziców i profesjonalistów z zakresu Stosowanej Analizy Zachowania w ramach Polskiej Licencji Terapeuty Behawioralnego. Pracuje jako wykładowca na Uniwersytecie SWPS w Warszawie, prowadząc zajęcia w ramach studiów podyplomowych „Stosowana Analiza Zachowania: przygotowanie do pracy z osobami z zaburzeniami rozwoju i zachowania”. Specjalizuje się w pracy nad zachowaniami trudnymi i uczeniu umiejętności społecznych. W życiu prywatnym z pasją oddaje się urządzaniu mieszkań.` },
	{ image: '/../assets/img/magdalena-bartoszko.png', position: 'Terapeuta TUS', name: 'Magdalena Bartoszko', description: `Pedagog specjalny, nauczyciel edukacji wczesnoszkolnej i przedszkolnej, nauczyciel wychowania fizycznego, Terapeuta Bilateralnej Integracji. Pracuje w szkole podstawowej specjalnej. Ukończyła kursy i szkolenia: Terapia behawioralna w teorii i praktyce - 3 modułowy kurs bazowy,	Techniki SAZ w pracy z osobą przejawiającą trudne zachowania, Techniki SAZ w rozwijaniu	mowy i komunikacji, Wspomaganie rozwoju dzieci ze specyficznymi problemami w nauce - Szkolny Program INTERWENCYJNY Sally Goddard Blythe oparty o integrację odruchów oraz	ocenę neuromotorycznej gotowości do nauki testem przesiewowym INPP, Terapia ręki I i II	stopnia, Psychomotoryka, Metoda Dobrego Startu, Metoda globalnego czytania, szkolenie z zakresu	diagnozy AAC.: Stosowanie oceny efektywności porozumiewania się dzieci niemówiących z użyciem narzędzia, Alternatywne sposoby porozumiewania się dzieci niepełnosprawnych - I i II	stopień, Trening Umiejętności Społecznych (TUS) terapia grupowa dzieci ze spektrum autyzmu.	W pracy z dzieckiem metody pracy dobiera odpowiednio do jego potrzeb tak, by mogło ono	osiągnąć najwyższy cel na miarę swoich możliwości.<br>
	Prywatnie mama dwójki dzieci, pasjonatka wszelkich form aktywności fizycznej, szczególnie tańca	oraz książek.` },
	{ image: '/../assets/img/karolina-grzesiak.png', position: 'Terapeuta TUS', name: 'Karolina Grzesiak', description: `Nauczyciel edukacji wczesnoszkolnej i przedszkolnej oraz pedagog specjalny.	Na co dzień pracuje w terapeutycznym punkcie przedszkolnym dla dzieci niepełnosprawnych.	Ukończyła kursy i szkolenia: Terapia ręki I i II stopnia, Techniki SAZ w szkole; terapia	behawioralna dzieci i młodzieży z zaburzeniami ze spektrum autyzmu, Metoda Ruchu	Rozwijającego Weroniki Sherborne I stopnia, Zachowania – chwile trudne albo tylko kłopotliwe,	jak sobie radzić z zachowaniami trudnymi dziecka; szkolenie dla opiekunów i rodziców dzieci z	autyzmem i Zespołem Aspergera oraz Terapia behawioralna w teorii i praktyce - III modułowy kurs	bazowy. Uczestniczyła w szkoleniu Trening Umiejętności Społecznych (TUS); terapia grupowa	dzieci ze spektrum autyzmu oraz zdała egzamin potwierdzający nabycie kompetencji niezbędnych	do prowadzenia i projektowania zajęć TUS.<br>
	Praca z dziećmi oraz pomaganie im w zrozumieniu świata i nabywaniu nowych umiejętności	dostarcza jej wiele satysfakcji, uczy pokory i cierpliwości.<br>
	Prywatnie miłośniczka jazdy na rowerze oraz mama dwóch córek w wieku przedszkolnym i	wczesnoszkolnym.` }
];